### PR TITLE
Fix state override accessing state

### LINKED ISSUE #8130: Gnosis mainnet : eth_call payload crashes with an error : System.InvalidOperationException
**Description**
Gnosis mainnet : `eth_call` crashes with -32603 error on Nethermind [v1.30.1](https://github.com/NethermindEth/nethermind/releases/tag/1.30.1)

**Steps to Reproduce**

```
curl localhost:8545 \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"id":1,"jsonrpc":"2.0","method":"eth_call","params":[{"from":"0x0000000000000000000000000000000000000000","to":"0xb50201558b00496a145fe76f7424749556e326d8","data":"0x35ea6a75000000000000000000000000cb444e90d8198415266c6a2724b7900fb12fc56e"},"latest"]}'
```

**Actual behavior**
```
{"jsonrpc":"2.0","error":{"code":-32603,"message":"Internal error","data":"System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.\n ---\u003E System.InvalidOperationException: Operation is not valid due to the current state of the object.\n   at Nethermind.Consensus.Processing.OverridableTxProcessingEnv.Nethermind.Evm.TransactionProcessing.IOverridableTxProcessorSource.BuildAndOverride(BlockHeader header, Dictionary\u00602 stateOverride) in /src/Nethermind/Nethermind.Consensus/Processing/OverridableTxProcessingEnv.cs:line 56\n   at Nethermind.Facade.BlockchainBridge.Call(BlockHeader header, Transaction tx, Dictionary\u00602 stateOverride, CancellationToken cancellationToken) in /src/Nethermind/Nethermind.Facade/BlockchainBridge.cs:line 153\n   at Nethermind.JsonRpc.Modules.Eth.ExecutorBase\u00603.Execute(TRequest call, BlockParameter blockParameter, Dictionary\u00602 stateOverride) in /src/Nethermind/Nethermind.JsonRpc/Modules/Eth/ExecutorBase.cs:line 31\n   at Nethermind.JsonRpc.Modules.Eth.EthRpcModule.eth_call(TransactionForRpc transactionCall, BlockParameter blockParameter, Dictionary\u00602 stateOverride) in /src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs:line 331\n   at InvokeStub_IEthRpcModule.eth_call(Object, Span\u00601)\n   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\n   --- End of inner exception stack trace ---\n   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\n   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\n   at Nethermind.JsonRpc.JsonRpcService.ExecuteAsync(JsonRpcRequest request, String methodName, ResolvedMethodInfo method, JsonRpcContext context) in /src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs:line 176"},"id":1}
```

**Expected behavior**
Not crash with -32603 internal error

**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
 - Operating System: [Linux]
 - Version: [Ubuntu 22.04.5 LTS]
 - Installation Method: [Docker]
 - Consensus Client: [Lighthouse v6.0.1]
 - Execution Client : [Nethermind v1.30.1]

### PR DESCRIPTION
**Pull request by LukaszRozmej**
Fixes #8130 and #7945

## Changes

- Doesn't bother trying to revert state root on json rpc, resets environment before accessing it

#### What types of changes does your code introduce?

- [x] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [x] No

#### Notes on testing

`eth_call`/`eth_estimateGas`/`eth_simulate`/`debug_traceXXX`/`trace_` fuzzing with state overrides

### CODE REVIEW

File: src/Nethermind/Nethermind.Consensus/Processing/OverridableTxProcessingScope.cs [hunk 1]
```diff
@@ -8,22 +8,34 @@
...
+        Hash256 stateRoot)
     {
-        worldState.StateRoot = originalStateRoot;
-        worldState.Reset();
-        worldState.ResetOverrides();
-        codeInfoRepository.ResetOverrides();
+        _codeInfoRepository = codeInfoRepository;
+        _transactionProcessor = transactionProcessor;
+        _worldState = worldState;
+        Reset();
```
Comment (alexb5dh) [inline src/Nethermind/Nethermind.Consensus/Processing/OverridableTxProcessingScope.cs:25]: So we are resetting state before each RPC call now (instead of doing it after override-only calls)?
Any estimations on performance impact?

**Review by alexb5dh — APPROVED** [review]

File: src/Nethermind/Nethermind.Consensus/Processing/OverridableTxProcessingScope.cs (hunk 1 above)
Comment (LukaszRozmej) [reply src/Nethermind/Nethermind.Consensus/Processing/OverridableTxProcessingScope.cs:25]: Probably minimal, just some `Clears` on collections, I would prefer to reset it on Dispose but we probably have some use cases where we leak it, so doing it like that for safety.

File: src/Nethermind/Nethermind.Consensus/Tracing/GethStyleTracer.cs [hunk 2]
```diff
@@ -125,6 +122,7 @@ public GethLikeTxTrace Trace(Hash256 blockHash, int txIndex, GethTraceOptions op
         if (tx.Hash is null) throw new InvalidOperationException("Cannot trace transactions without tx hash set.");
 
         block = block.WithReplacedBodyCloned(BlockBody.WithOneTransactionOnly(tx));
+        using IOverridableTxProcessingScope? scope = _env.BuildAndOverride(block.Header, options.StateOverrides);
```
Comment (alexb5dh) [inline src/Nethermind/Nethermind.Consensus/Tracing/GethStyleTracer.cs:125]: I don't think `scope` needs to be nullable here and in other places.
