### PR TITLE
Fix transactions pointing to wrong block

### LINKED ISSUE #3052: On reorgs we can have transaction pointing to wrong block
After reorg eth_getTransactionReceipt returns block that lost, both blocks included that transaction.

curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xd225ebf954dff3554e36511f0094a36c2e281fff7831bf35a74d6bd953df9c6c"],"id":1}' https://core-archive.blockscout.com

[0xd225ebf954dff3554e36511f0094a36c2e281fff7831bf35a74d6bd953df9c6c.txt](https://github.com/NethermindEth/nethermind/files/6468103/0xd225ebf954dff3554e36511f0094a36c2e281fff7831bf35a74d6bd953df9c6c.txt)

curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByHash","params":["0xe032ec288e3eb2235211795cf48c423643730feb84d335aa27eb2cec7abc0525", true],"id":1}' https://core-archive.blockscout.com

[0xe032ec288e3eb2235211795cf48c423643730feb84d335aa27eb2cec7abc0525.txt](https://github.com/NethermindEth/nethermind/files/6468102/0xe032ec288e3eb2235211795cf48c423643730feb84d335aa27eb2cec7abc0525.txt)

curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByHash","params":["0x04e0dbe0b367db8be8a72c5355bb002ca229a33b61913be1c0657a6e632ecc48", true],"id":1}' https://core-archive.blockscout.com

[0x04e0dbe0b367db8be8a72c5355bb002ca229a33b61913be1c0657a6e632ecc48.txt](https://github.com/NethermindEth/nethermind/files/6468101/0x04e0dbe0b367db8be8a72c5355bb002ca229a33b61913be1c0657a6e632ecc48.txt)

curl -X POST --data '{"jsonrpc":"2.0","method":"debug_getChainLevel","params":["0x142e692"],"id":1}' https://core-archive.blockscout.com

[0x142e692.txt](https://github.com/NethermindEth/nethermind/files/6468099/0x142e692.txt)

### PR DESCRIPTION
**Pull request by marcindsobczak**
Resolves #3052

## Changes:

While adding eth_subscribe I added class ReceiptCanonicalityMonitor, which is getting receipts of old blocks (after reorganization), is changing flag "Removed" to true and inserting these changed receipts (and these rollbacked receipts are sended to subscribers).

Inside PersistentReceiptStorage, in method Insert, we are setting in DB reference from tx to block and it was overwritten by removed txs.

I changed it to be overwritten only if flag "Removed" of TxReceipt is false.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [x] Yes
- [ ] No

**In case you checked yes, did you write tests??**

- [x] Yes
- [ ] No

### CODE REVIEW

File: src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs [hunk 1]
```diff
@@ -227,8 +227,11 @@ public void Insert(Block block, params TxReceipt[] txReceipts)
             
             for (int i = 0; i < txReceipts.Length; i++)
             {
-                var txHash = block.Transactions[i].Hash;
-                _transactionDb.Set(txHash, block.Hash.Bytes);
+                if (txReceipts[i].Removed == false)
```
Comment (LukaszRozmej) [inline src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs:230]: !txReceipts[i].Removed and We can check it for first item outside of for loop, we don't expect mixed batches

**Review by LukaszRozmej — APPROVED** [review]

**Review by MarekM25 — APPROVED** [review]

File: src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs (hunk 1 above)
Comment (marcindsobczak) [reply src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs]: Done
