### PR TITLE
Calculate Tx Hash if fast path not available

### LINKED ISSUE #6663: Sepolia transaction can't be found
**Description**
Specific transaction can't be found by sepolia nethermind node, while it can be found in the list of transactions in the block which contains it.

**Steps to Reproduce**
Issue a request on Sepolia Nethermind node and no tx was found:

`{"method":"eth_getTransactionByHash","params":["0xaa634f11a3818c701f292e89e8a7c40a0a9a8c91cc7783956a1a5d4198d6d1b7"],"id":1,"jsonrpc":"2.0"}`

Response: 
```
{
    "jsonrpc": "2.0",
    "result": null,
    "id": 1
}
```

Issuing another request on the same Sepolia Nethermind node:

`{"method":"eth_getBlockByNumber","params":["0x4FE3DE"],"id":1,"jsonrpc":"2.0"}`

and the transaction `0xaa634f11a3818c701f292e89e8a7c40a0a9a8c91cc7783956a1a5d4198d6d1b7` can be found under the "transactions" field.

By the way, I tried searching for other transactions from the problematic block, and it seems none of them can be fetched.

**Actual behavior**
No tx is found.

**Expected behavior**
Transaction can be found by hash.

**Desktop (please complete the following information):**
Version: 1.25.3
Commit: e64bee7033c6d74cb53323b703cb573a739cd9dd
Build Date: 2024-01-22 15:11:29Z
OS: Linux x64
Runtime: .NET 8.0.1

### LINKED ISSUE #6670: Attempted to process a blockchain without having starting state
**Description**
Block processing or recovery after restart leads to broken state, restart helped at least in one case.

**Steps to Reproduce**
Run the node/restart it

**Actual behavior**
Node stucks reporting "Exception: System.InvalidOperationException: Attempted to process a blockchain without having starting state"

**Expected behavior**
Startup recovery and block processing is OK

**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
 - Operating System: Linux x64
 - Version: 1.25.3
 - Installation Method: docker
 - Consensus Client: lighthouse, nimbus

**Additional context**
Please provide any additional context about the problem.

**Logs**

```
nethermind-lh_1        | 04 Feb 00:02:56 | Processed    10480679... 10480680 |  1,167.85 ms  |  slot      1,172 ms | Gas gwei: 0.00 .. 0.00 (0.31) .. 5.00 
nethermind-lh_1        | 04 Feb 00:02:56 | - Blocks 2            3.34 MGas   |     72    txs |  calls    102 (  4) | sload     456 | sstore    128 | create   0 
nethermind-lh_1        | 04 Feb 00:02:56 | - Block throughput    2.86 MGas/s |     61.65 t/s |          1.71 Blk/s | recv        0 | proc       88 
nethermind-lh_1        | 04 Feb 00:02:57 | Processed            10480681     |  1,412.70 ms  |  slot      1,416 ms | Gas gwei: 0.00 .. 0.00 (0.29) .. 18.00 
nethermind-lh_1        | 04 Feb 00:02:57 | - Block               5.04 MGas   |    158    txs |  calls     94 (  2) | sload     317 | sstore     87 | create   0 
nethermind-lh_1        | 04 Feb 00:02:57 | - Block throughput    3.57 MGas/s |    111.84 t/s |          0.71 Blk/s | recv        0 | proc       87 
nethermind-lh_1        | 04 Feb 00:02:59 | Processed            10480682     |  1,558.34 ms  |  slot      1,560 ms | Gas gwei: 0.00 .. 0.00 (0.13) .. 6.00 
nethermind-lh_1        | 04 Feb 00:02:59 | - Block               7.23 MGas   |    183    txs |  calls    216 (  2) | sload     847 | sstore    181 | create   0 
nethermind-lh_1        | 04 Feb 00:02:59 | - Block throughput    4.64 MGas/s |    117.43 t/s |          0.64 Blk/s | recv        0 | proc       86 
nethermind-lh_1        | 04 Feb 00:03:01 | Processed            10480683     |  2,346.91 ms  |  slot      2,348 ms | Gas gwei: 0.00 .. 0.00 (0.07) .. 6.00 
nethermind-lh_1        | 04 Feb 00:03:01 | - Block               9.70 MGas   |    321    txs |  calls     81 (  3) | sload     315 | sstore    109 | create   0 
nethermind-lh_1        | 04 Feb 00:03:01 | - Block throughput    4.13 MGas/s |    136.78 t/s |          0.43 Blk/s | recv        0 | proc       85 
nethermind-lh_1        | 04 Feb 00:03:01 | Received new block:  10480769 (0x3dfba8...22f76e) 
nethermind-lh_1        | 04 Feb 00:03:01 | Processing loop threw an exception. Block: 10480685 (0xdfb77c...a6e7cd), Exception: System.InvalidOperationException: Attempted to process a blockchain without having starting state
nethermind-lh_1        |    at Nethermind.Consensus.Processing.BlockchainProcessor.PrepareBlocksToProcess(Block suggestedBlock, ProcessingOptions options, ProcessingBranch processingBranch) in /_/src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 576
nethermind-lh_1        |    at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer) in /_/src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 384
nethermind-lh_1        |    at Nethermind.Consensus.Processing.BlockchainProcessor.RunProcessingLoop() in /_/src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 317 
nethermind-lh_1        | 04 Feb 00:03:01 | Processing loop threw an exception. Block: 10480686 (0xba4ff6...8c2c7e), Exception: System.InvalidOperationException: Attempted to process a blockchain without having starting state
nethermind-lh_1        |    at Nethermind.Consensus.Processing.BlockchainProcessor.PrepareBlocksToProcess(Block suggestedBlock, ProcessingOptions options, ProcessingBranch processingBranch) in /_/src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 576
nethermind-lh_1        |    at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer) in /_/src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 384
nethermind-lh_1        |    at Nethermind.Consensus.Processing.BlockchainProcessor.RunProcessingLoop() in /_/src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 317
```

another case after restart
```
execution-1  | 05 Feb 10:56:52 | Rerunning block after reorg or pruning: 810888 (0x6ec590...f2c637) 
execution-1  | 05 Feb 10:56:52 | Rerunning block after reorg or pruning: 810889 (0x353973...e6c062) 
execution-1  | 05 Feb 10:56:52 | Rerunning block after reorg or pruning: 810890 (0xb42948...1cd3fc) 
execution-1  | 05 Feb 10:56:53 | Rerunning block after reorg or pruning: 810891 (0x2b9e28...e4d4d2) 
execution-1  | 05 Feb 10:56:53 | Rerunning block after reorg or pruning: 810892 (0xc6b947...4e7d53) 
execution-1  | 05 Feb 10:56:53 | Rerunning block after reorg or pruning: 810893 (0xad0ad5...4300de) 
execution-1  | 05 Feb 10:56:53 | Rerunning block after reorg or pruning: 810894 (0x05aa2f...0b66b7) 
execution-1  | 05 Feb 10:56:53 | Rerunning block after reorg or pruning: 810895 (0x2b941d...07a912) 
execution-1  | 05 Feb 10:56:53 | Processed      810886...   810895 |  1,051.79 ms  |  slot      1,053 ms | Gas gwei: 1.12 .. [97m1.12[37m (1.65) .. 3.00 
execution-1  | 05 Feb 10:56:53 | - Blocks 10         144.39[37m MGas   |    186    txs |  calls  5,089[37m [37m( 17)[37m | sload  12,747 | sstore  7,275[37m | create 1,307[37m[37m(-1,006)[37m 
execution-1  | 05 Feb 10:56:53 | - Block throughput  137.28 MGas/s |    176.84 t/s |          9.51 Blk/s | recv    5,966 | proc    2,000 
execution-1  | 05 Feb 10:56:53 | Rerunning block after reorg or pruning: 810896 (0x673fc3...06478b) 
execution-1  | 05 Feb 10:56:53 | Processing loop threw an exception. Block: 810898 (0xd20dc7...cdc856), Exception: System.InvalidOperationException: Attempted to process a blockchain without having starting state
execution-1  |    at Nethermind.Consensus.Processing.BlockchainProcessor.PrepareBlocksToProcess(Block suggestedBlock, ProcessingOptions options, ProcessingBranch processingBranch) in /_/src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 576
execution-1  |    at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer) in /_/src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 384
execution-1  |    at Nethermind.Consensus.Processing.BlockchainProcessor.RunProcessingLoop() in /_/src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 317 
```

### PR DESCRIPTION
**Pull request by benaadams**
Resolves #6663 though would need resync
Resolves #6670

## Changes

- Perform the full Rlp hash if fast path not available

#### What types of changes does your code introduce?

- [x] Bugfix (a non-breaking change that fixes an issue)

#### Requires testing

- [x] No

### CODE REVIEW

File: src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs [hunk 1]
```diff
@@ -358,14 +359,16 @@ public void EnsureCanonical(Block block)
             {
                 foreach (Transaction tx in block.Transactions)
                 {
-                    writeBatch[tx.Hash.Bytes] = Rlp.Encode(block.Number).Bytes;
+                    Hash256 hash = (tx.Hash ??= tx.CalculateHash());
+                    writeBatch[hash.Bytes] = Rlp.Encode(block.Number).Bytes;
```
Comment (LukaszRozmej) [inline src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs:363]: we should do this once before the loop, also we can probably use PutSpan to avoid allocating

File: src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs [hunk 2]
```diff
@@ -358,14 +359,16 @@ public void EnsureCanonical(Block block)
...
                 }
             }
             else
             {
                 foreach (Transaction tx in block.Transactions)
                 {
-                    writeBatch[tx.Hash.Bytes] = block.Hash.BytesToArray();
+                    Hash256 hash = (tx.Hash ??= tx.CalculateHash());
+                    writeBatch[hash.Bytes] = block.Hash.BytesToArray();
```
Comment (LukaszRozmej) [inline src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs:371]: we should do this once before the loop, also we can probably use PutSpan to avoid allocating

**Review by LukaszRozmej — APPROVED** [review]

File: src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs (hunk 1 above)
Comment (benaadams) [reply src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs]: Moved. Not sure the WriteBatch supports PutSpan

File: src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs (hunk 2 above)
Comment (benaadams) [reply src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs]: Moved
