### PR TITLE
Fix gapless reverse blockheader search

### LINKED ISSUE #5017: GetBlockHeaders, Reverse: true
`Reverse: true` is not honoured
More details: https://github.com/ledgerwatch/erigon/issues/6308
https://github.com/ethereum/devp2p/blob/master/caps/eth.md#getblockheaders-0x03

### PR DESCRIPTION
**Pull request by LukaszRozmej**
Fixes #5017

## Changes:
- Fix for faster version of `GetBlockHeaders` to properly support `reverse` flag.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [x] Yes
- [ ] No

**In case you checked yes, did you write tests??**

- [x] Yes
- [ ] No

### CODE REVIEW

File: src/Nethermind/Nethermind.Blockchain/BlockTree.cs [hunk 1]
```diff
@@ -946,14 +946,48 @@ public BlockHeader[] FindHeaders(Keccak? blockHash, int numberOfBlocks, int skip
 
             if (skip == 0)
             {
+                static BlockHeader[] FindHeadersReversedFast(BlockTree tree, BlockHeader startHeader, int numberOfBlocks, bool reverse = false)
```
Comment (asdacap) [inline src/Nethermind/Nethermind.Blockchain/BlockTree.cs:949]: Why move in?

File: src/Nethermind/Nethermind.Blockchain/BlockTree.cs [hunk 2]
```diff
@@ -946,14 +946,48 @@ public BlockHeader[] FindHeaders(Keccak? blockHash, int numberOfBlocks, int skip
...
+                    {
+                        result[responseIndex] = current;
+                        responseIndex += step;
+                        if (responseIndex < 0)
+                        {
+                            break;
+                        }
+
+                        current = tree.FindParentHeader(current, BlockTreeLookupOptions.TotalDifficultyNotNeeded);
+                    } while (current is not null && responseIndex < numberOfBlocks);
```
Comment (asdacap) [inline src/Nethermind/Nethermind.Blockchain/BlockTree.cs:972]: Shouldn't you add `responseIndex > 0` for forward also?

File: src/Nethermind/Nethermind.Blockchain.Test/BlockTreeTests.cs [hunk 3]
```diff
@@ -433,9 +433,13 @@ public void Find_headers_reverse()
             Block block0 = Build.A.Block.WithNumber(0).TestObject;
             Block block1 = Build.A.Block.WithNumber(1).WithParent(block0).TestObject;
             Block block2 = Build.A.Block.WithNumber(2).WithParent(block1).TestObject;
+            Block block3 = Build.A.Block.WithNumber(3).WithParent(block2).TestObject;
+            Block block4 = Build.A.Block.WithNumber(4).WithParent(block3).TestObject;
             AddToMain(blockTree, block0);
             AddToMain(blockTree, block1);
             AddToMain(blockTree, block2);
+            AddToMain(blockTree, block3);
+            AddToMain(blockTree, block4);
```
Comment (asdacap) [inline src/Nethermind/Nethermind.Blockchain.Test/BlockTreeTests.cs:442]: Why this did not catch the issue before? Should you update this test somehow on line 444?

File: src/Nethermind/Nethermind.Blockchain/BlockTree.cs (hunk 1 above)
Comment (LukaszRozmej) [reply src/Nethermind/Nethermind.Blockchain/BlockTree.cs:949]: To be closer to only place where it is used.

File: src/Nethermind/Nethermind.Blockchain.Test/BlockTreeTests.cs (hunk 3 above)
Comment (LukaszRozmej) [reply src/Nethermind/Nethermind.Blockchain.Test/BlockTreeTests.cs:442]: BlockTree didn't have any blocks past the requested one, which caused `endBlock` - how it was previously calculated to always be `null`

**Review by asdacap — APPROVED** [review]
