### PR TITLE
Fix/arg out of range SnapProvider.AddAccountRange

### LINKED ISSUE #7033: [Holesky] ArgumentOutOfRangeException during sync
During a sync of Holesky on SnapSync the below exception is getting thrown.

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at Nethermind.Core.Collections.ArrayPoolList`1.<GuardIndex>g__ThrowArgumentOutOfRangeException|54_0() in /_/src/Nethermind/Nethermind.Core/Collections/ArrayPoolList.cs:line 307
   at Nethermind.Synchronization.SnapSync.SnapProviderHelper.AddAccountRange(StateTree tree, Int64 blockNumber, ValueHash256& expectedRootHash, ValueHash256& startingHash, ValueHash256& limitHash, IReadOnlyList`1 accounts, IReadOnlyList`1 proofs) in /_/src/Nethermind/Nethermind.Synchronization/SnapSync/SnapProviderHelper.cs:line 50
   at Nethermind.Synchronization.SnapSync.SnapProvider.AddAccountRange(Int64 blockNumber, ValueHash256& expectedRootHash, ValueHash256& startingHash, IReadOnlyList`1 accounts, IReadOnlyList`1 proofs, Nullable`1& hashLimit) in /_/src/Nethermind/Nethermind.Synchronization/SnapSync/SnapProvider.cs:line 85
   at Nethermind.Synchronization.SnapSync.SnapProvider.AddAccountRange(AccountRange request, AccountsAndProofs response) in /_/src/Nethermind/Nethermind.Synchronization/SnapSync/SnapProvider.cs:line 62
   at Nethermind.Synchronization.SnapSync.SnapSyncFeed.HandleResponse(SnapSyncBatch batch, PeerInfo peer) in /_/src/Nethermind/Nethermind.Synchronization/SnapSync/SnapSyncFeed.cs:line 63
   at Nethermind.Synchronization.ParallelSync.SyncDispatcher`1.DoHandleResponse(T request, PeerInfo allocatedPeer) in /_/src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncDispatcher.cs:line 186
```

Not sure now about side effects of it but needs to be investigated as it is first time it appears.

### PR DESCRIPTION
**Pull request by ak88**
Fixes #7033

## Changes
`SnapProvider.AddAccountRange`  will now throw in case of empty account list , and
`AddAccountRange(AccountRange request, AccountsAndProofs response)`  will return `ExpiredRootHash` in case of empty account list.

#### What types of changes does your code introduce?

- [x] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

### CODE REVIEW

File: src/Nethermind/Nethermind.Synchronization/SnapSync/SnapProviderHelper.cs [hunk 1]
```diff
@@ -31,7 +32,8 @@ public static class SnapProviderHelper
         )
         {
             // TODO: Check the accounts boundaries and sorting
-
+            if (!accounts.Any())
```
Comment (LukaszRozmej) [inline src/Nethermind/Nethermind.Synchronization/SnapSync/SnapProviderHelper.cs:35]: avoid Linq, check Count

File: src/Nethermind/Nethermind.Synchronization/SnapSync/SnapProvider.cs [hunk 2]
```diff
@@ -73,8 +79,16 @@ public AddRangeResult AddAccountRange(AccountRange request, AccountsAndProofs re
...
-        public AddRangeResult AddAccountRange(long blockNumber, in ValueHash256 expectedRootHash, in ValueHash256 startingHash, IReadOnlyList<PathWithAccount> accounts, IReadOnlyList<byte[]> proofs = null, in ValueHash256? hashLimit = null!)
+        public AddRangeResult AddAccountRange(
+            long blockNumber,
+            in ValueHash256 expectedRootHash,
+            in ValueHash256 startingHash,
+            IReadOnlyList<PathWithAccount> accounts,
+            IReadOnlyList<byte[]> proofs = null,
+            in ValueHash256? hashLimit = null!)
         {
+            if (!accounts.Any())
```
Comment (LukaszRozmej) [inline src/Nethermind/Nethermind.Synchronization/SnapSync/SnapProvider.cs:90]: avoid LINQ, check count

File: src/Nethermind/Nethermind.Synchronization.Test/UnpooledReadOnlyList.cs [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+using System.Linq;
+using System.Text;
+using System.Threading.Tasks;
+
+namespace Nethermind.Synchronization.Test;
+/// <summary>
+/// This is list that does not require disposing and is meant for test purposes.
+/// </summary>
+/// <typeparam name="T"></typeparam>
+internal class UnpooledReadOnlyList<T> : List<T>, IOwnedReadOnlyList<T>
```
Comment (LukaszRozmej) [inline src/Nethermind/Nethermind.Synchronization.Test/UnpooledReadOnlyList.cs:17]: Is it needed?

File: src/Nethermind/Nethermind.Synchronization.Test/SnapSync/SnapProviderTests.cs [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+    [Test]
+    public void AddAccountRange_ResponseHasEmptyListOfAccountsAndOneProof_ReturnsExpiredRootHash()
+    {
+        MemDb db = new();
+        IDbProvider dbProvider = new DbProvider();
+        dbProvider.RegisterDb(DbNames.State, db);
+        using ProgressTracker progressTracker = new(Substitute.For<IBlockTree>(), dbProvider.GetDb<IDb>(DbNames.State), LimboLogs.Instance);
+        dbProvider.RegisterDb(DbNames.Code, new MemDb());
+        AccountRange accountRange = new(Keccak.Zero, Keccak.Zero, Keccak.MaxValue);
+        AccountsAndProofs accountsAndProofs = new();
```
Comment (LukaszRozmej) [inline src/Nethermind/Nethermind.Synchronization.Test/SnapSync/SnapProviderTests.cs:52]:
```suggestion
        using AccountsAndProofs accountsAndProofs = new();
```

**Review by LukaszRozmej — CHANGES_REQUESTED** [review]

File: src/Nethermind/Nethermind.Synchronization.Test/UnpooledReadOnlyList.cs (hunk 3 above)
Comment (ak88) [reply src/Nethermind/Nethermind.Synchronization.Test/UnpooledReadOnlyList.cs:17]: It was to avoid `using` everytime you new up a request or response in the tests. But if the convention is to go with using, i can remove it.

Comment (LukaszRozmej) [reply src/Nethermind/Nethermind.Synchronization.Test/UnpooledReadOnlyList.cs:17]: It is good to be reminded that you need to dispose! :)

**Review by LukaszRozmej — APPROVED** [review]

**Review by asdacap — APPROVED** [review]

**Review by benaadams — APPROVED** [review]
