### PR TITLE
Fix eth_getlogs not returning error when receipt is unavailable

### LINKED ISSUE #3983: Fix eth_getLogs - return error when syncing/receipt not available
**Describe the bug**
When syncing eth_getLogs doesn't return NotFound when syncing and not having correct data.

**To Reproduce**
1. Sync node
2. Ask eth_getLogs for not downloaded receipts
3. Partial results are given

**Expected behavior**
Should return an error that data isn't there

### PR DESCRIPTION
**Pull request by asdacap**
Fixes #3983

## Changes:
- Added `HasBlock` method to `IReceiptStorage`.
  - `ReceiptPersistentStorage` implemented it by checking its cache first, then the blocks column.
- `LogFinder` will check `HasBlock` on first and last block and will throw `ResourceNotFoundException` if receipt not found.
- `EthRpcModule` will return resource not found code when `ResourceNotFoundException` is encountered.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
- [ X] Yes
- [ ] No

**In case you checked yes, did you write tests??**

- [ X] Yes
- [ ] No

**Comments about testing , should you have some** (optional)

- Tested by running a clean DB. During fast sync after header was downloaded, query for block where the header already download. Confirmed error is returned.
- Queried again after full sync. Confirmed logs was returned.

### CODE REVIEW

**Comment by LukaszRozmej** [comment]
Generally fine, but I think here we are clipping to block, do we want to do that?
https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Blockchain/Find/LogFinder.cs#L69

Other small thing not sure if it should be ResourceNotFound or ResourceUnavailable?

**Comment by asdacap** [comment]
Missed the clip thing.

As for the ResourceNotFound or ResourceUnavailable, it seems that other RPC that can't run when state is unavailable respond with ResourceUnavailable, but currently, if the block is not found (as in header not found, not just receipt), it returns, resourceNotFound. So.. I don't know.

File: src/Nethermind/Nethermind.Blockchain/Find/LogFinder.cs [hunk 1]
```diff
@@ -63,18 +63,29 @@ public class LogFinder : ILogFinder
         public IEnumerable<FilterLog> FindLogs(LogFilter filter, CancellationToken cancellationToken = default)
         {
             BlockHeader FindHeader(BlockParameter blockParameter, string name, bool headLimit) => 
-                _blockFinder.FindHeader(blockParameter, headLimit) ?? throw new ArgumentException("Block not found.", name);
+                _blockFinder.FindHeader(blockParameter, headLimit) ?? throw new ResourceNotFoundException($"Block not found: {name}");
 
             cancellationToken.ThrowIfCancellationRequested();
-            var toBlock = FindHeader(filter.ToBlock, nameof(filter.ToBlock), true);
+            var toBlock = FindHeader(filter.ToBlock, nameof(filter.ToBlock), false);
```
Comment (LukaszRozmej) [inline src/Nethermind/Nethermind.Blockchain/Find/LogFinder.cs:69]: Now its possible for this to return null too. Shouldn't we throw here too?

File: src/Nethermind/Nethermind.Blockchain/Find/LogFinder.cs [hunk 2]
```diff
@@ -63,18 +63,29 @@ public class LogFinder : ILogFinder
         public IEnumerable<FilterLog> FindLogs(LogFilter filter, CancellationToken cancellationToken = default)
         {
             BlockHeader FindHeader(BlockParameter blockParameter, string name, bool headLimit) => 
-                _blockFinder.FindHeader(blockParameter, headLimit) ?? throw new ArgumentException("Block not found.", name);
+                _blockFinder.FindHeader(blockParameter, headLimit) ?? throw new ResourceNotFoundException($"Block not found: {name}");
```
Comment (LukaszRozmej) [inline src/Nethermind/Nethermind.Blockchain/Find/LogFinder.cs:66]: Can we also include BlockParameter in error message?

File: src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs [hunk 3]
```diff
@@ -656,8 +654,16 @@ public ResultWrapper<IEnumerable<FilterLog>> eth_getLogs(Filter filter)
...
+            try
+            {
+                IEnumerable<FilterLog> filterLogs = _blockchainBridge.GetLogs(filter.FromBlock, filter.ToBlock,
+                    filter.Address, filter.Topics, cancellationToken);
+                return ResultWrapper<IEnumerable<FilterLog>>.Success(GetLogs(filterLogs, cancellationTokenSource));
+            }
+            catch (ResourceNotFoundException exception)
+            {
+                return ResultWrapper<IEnumerable<FilterLog>>.Fail(exception.Message, ErrorCodes.ResourceNotFound);
+            }
```
Comment (LukaszRozmej) [inline src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs:666]: Generally this is lazy collection, does it throw without enumeration (maybe yes as its before first yield)?

File: src/Nethermind/Nethermind.Blockchain/Find/LogFinder.cs (hunk 1 above)
Comment (asdacap) [reply src/Nethermind/Nethermind.Blockchain/Find/LogFinder.cs:69]: It will throw in line 66.

File: src/Nethermind/Nethermind.Blockchain/Find/LogFinder.cs (hunk 2 above)
Comment (asdacap) [reply src/Nethermind/Nethermind.Blockchain/Find/LogFinder.cs:66]: Seems to already do it via the `name` parameter.

File: src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs (hunk 3 above)
Comment (asdacap) [reply src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs:666]: It should throw before the iterator is returned.

Comment (asdacap) [reply src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs:666]: As in, the line 659, not in line 618.

File: src/Nethermind/Nethermind.Blockchain/Find/LogFinder.cs (hunk 2 above)
Comment (LukaszRozmej) [reply src/Nethermind/Nethermind.Blockchain/Find/LogFinder.cs]: No its just nameof(filter.ToBlock), lets add what was that what we are missing (blocknumber, hash)

File: src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs (hunk 3 above)
Comment (LukaszRozmej) [reply src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs:666]: But its still lazy right?

Comment (asdacap) [reply src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs:666]: The iteration is still lazy. I move the call outside the function specifically so that it throws outside iteration. Otherwise, the exception will not be caught.

File: src/Nethermind/Nethermind.Blockchain/Find/LogFinder.cs (hunk 2 above)
Comment (asdacap) [reply src/Nethermind/Nethermind.Blockchain/Find/LogFinder.cs]: Ok, I suppose a simple `.ToString()` is enough?

Comment (LukaszRozmej) [reply src/Nethermind/Nethermind.Blockchain/Find/LogFinder.cs]: yes just drop it somewhere in the pattern in some good way

**Review by LukaszRozmej — APPROVED** [review]
