### PR TITLE
[Fix] `MultiSyncModeSelector`.`Changed` event propagation being blocked by SyncFeed

### LINKED ISSUE #6481: [Old Bodies] On already synced node it switches to FastBodies and stays there for about 1 minute without progress
**Steps to Reproduce**
In order to replicate the behavior, please provide a detailed list of steps:
1. Have synced node (on older version)
2. Restart it on 1.25.0
3. Monitor logs

**Actual behavior**
These logs appears:
```
08 Jan 14:53:31 | Sync mode changed from DbLoad to WaitingForBlock, FastBodies
08 Jan 14:53:31 | SyncDispatcher<BodiesSyncBatch> has finished work.
08 Jan 14:53:31 | Fast blocks bodies task completed.
08 Jan 14:53:32 | Changing state WaitingForBlock, FastBodies to WaitingForBlock, FastReceipts at processed: 18962940 | state: 18962940 | block: 18963005 | header: 18963005 | target block: 18963007 | peer block: 18963007
08 Jan 14:53:32 | Changed pivot in receipts sync. Now using pivot 18526686 and barrier 1
08 Jan 14:53:33 | Peers | with best block: 5 | all: 5 | eth66 (20 %), eth68 (80 %) | Active: None | Sleeping: All | Geth (40 %), Nethermind (20 %), Erigon (20 %), Unknown (20 %)
08 Jan 14:53:33 | Old Bodies   18,526,686 / 18,526,686 (100.00 %) | queue         0 | current            0 Blk/s | total            0 Blk/s
08 Jan 14:53:38 | Old Bodies   18,526,686 / 18,526,686 (100.00 %) | queue         0 | current            0 Blk/s | total            0 Blk/s
08 Jan 14:53:43 | Old Bodies   18,526,686 / 18,526,686 (100.00 %) | queue         0 | current            0 Blk/s | total            0 Blk/s
08 Jan 14:53:48 | Old Bodies   18,526,686 / 18,526,686 (100.00 %) | queue         0 | current            0 Blk/s | total            0 Blk/s
08 Jan 14:53:53 | Old Bodies   18,526,686 / 18,526,686 (100.00 %) | queue         0 | current            0 Blk/s | total            0 Blk/s
08 Jan 14:53:58 | Old Bodies   18,526,686 / 18,526,686 (100.00 %) | queue         0 | current            0 Blk/s | total            0 Blk/s
08 Jan 14:54:01 | SyncDispatcher<ReceiptsSyncBatch> has finished work.
```

**Expected behavior**
Old Bodies were synced (like a whole node) so these steps should not be triggered.

### PR DESCRIPTION
**Pull request by smartprogrammer93**
Fixes #6481

## Changes

- `SyncFeed`'s `Intialize` method takes a while. Call to it made async.
- Log messages are only printed out once SyncFeed finishes initialization.

#### What types of changes does your code introduce?

- [x] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [x] Yes
- [ ] No

#### Requires documentation update

- [ ] Yes
- [x] No

#### Requires explanation in Release Notes

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by benaadams — APPROVED** [review]

**Review by benaadams — APPROVED** [review]
Interesting solution! 😊

File: src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs [hunk 1]
```diff
@@ -281,7 +281,11 @@ private void UpdateSyncModes(SyncMode newModes, string? reason = null)
             Preparing?.Invoke(this, args);
             Changing?.Invoke(this, args);
             Current = newModes;
-            Changed?.Invoke(this, args);
+            if (Changed is not null)
+            {
+                Parallel.ForEach(Changed.GetInvocationList(),
+                    deleg => deleg.DynamicInvoke(this, args));
+            }
```
Comment (LukaszRozmej) [inline src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs:288]: I think it should not happen, but in theory pattern is to do a local copy to avoid `NullReferenceException` and be thread-safe:

https://stackoverflow.com/questions/33166143/local-copy-of-event

**Review by LukaszRozmej — COMMENTED** [review]
Why this is solving the issue? What is the technical cause of the issue?

**Comment by asdacap** [comment]
What was the problem?

File: src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs (hunk 1 above)
Comment (smartprogrammer93) [reply src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs:288]: 😲 You learn something every day

**Comment by benaadams** [comment]
> What was the problem?

Multiple events subscribed to the event; important one is second, first one takes a while

**Comment by smartprogrammer93** [comment]
@LukaszRozmej not entirely sure which delegate is blocking the invocation. also, parallelizing the the delegate method could lead to its own problems in my opinion (with concurrency and race conditions). Additionally, This solution guarantees that all delegates finish executing before continuing to execute the rest of the code.

**Comment by smartprogrammer93** [comment]
I will not merge this till it is properly tested and be sure it will resolve the issue. @kamilchodola  waiting on your confirmation, as i am not sure how exactly you were able to produce it. was not able to do so.

**Comment by LukaszRozmej** [comment]
> @LukaszRozmej not entirely sure which delegate is blocking the invocation. also, parallelizing the the delegate method could lead to its own problems in my opinion (with concurrency and race conditions). Additionally, This solution guarantees that all delegates finish executing before continuing to execute the rest of the code.

Well it makes it explicit and something to handle by the end-user, which actually allows for proper handling of race conditions. Now it is hidden.

**Review by flcl42 — COMMENTED** [review]
Can we make sync to start only when migrations are done?

**Comment by LukaszRozmej** [comment]
> > What was the problem?
> 
> Multiple events subscribed to the event; important one is second, first one takes a while to return and they are executed in order

I would execute first one parallel explicitly in the handler, don't you think it is better?

**Comment by smartprogrammer93** [comment]
@LukaszRozmej i disagree. since if another syncmode change happens while the handler is still executing the previous one it could lead to a race condition.
With this approach, the parallel for guarantees the execution of all of the handlers is done before it releases the thread possibly blocking syncmode from switching before all the previous handlers have already finished execution.

**Review by LukaszRozmej — APPROVED** [review]

**Comment by kamilchodola** [comment]
@smartprogrammer93 @LukaszRozmej what about this one?

**Comment by smartprogrammer93** [comment]
Ready from my side. Feel free to merge it if no more testing is needed.  @kamilchodola
