### PR TITLE
Fix history prune scheduling

### LINKED ISSUE #9697: "Unable to write to background task queue" exception
Yesterday I got this: "BlockchainProcessor encountered an exception. System.InvalidOperationException: Unable to write to background task queue."

I'm using Nethermind 1.35.2 on Windows 11 23H2. I'm using --History.Pruning Rolling. I'm using Prysm as a Beacon Node. The Nethermind db is super new (I had to remake it 2 days ago because I had a full disk). Not know if related, but at the same time I was deleting some hundred gb of other files on the same M.2 disk (there was more than 1TB of free space). Nethermind didn't crash, but just to be sure I rebooted the Nethermind. I've noticed that until when I rebooted the Nethermind there were no more "Pruning historical blocks up to timestamp" messages. I imagine the task had died.

2025-11-12 14:37:12.9157|INFO|Consensus.Processing.ProcessingStats|18|Processed            23783489         |      153.8 ms  | slot         12,195 ms |⛽ Gas gwei: 0.13 .. 1.17 (22.89) .. 217.84 
2025-11-12 14:37:12.9157|INFO|Consensus.Processing.ProcessingStats|18| Block    0.2830 ETH     5.71 MGas    |       37   txs | calls        395 ( 26) | sload   1,126 | sstore    401 | create   0 
2025-11-12 14:37:12.9157|INFO|Consensus.Processing.ProcessingStats|18| Block throughput       37.13 MGas/s  |      240.6 tps | blobs   0 | exec code cache     826 | new      4 | ops     351,078 
2025-11-12 14:37:12.9157|INFO|History.HistoryPruner|14|Pruning historical blocks up to timestamp 1731418619 (#23773081). Estimated 0 blocks will be deleted. 
2025-11-12 14:37:12.9157|INFO|History.HistoryPruner|14|Completed pruning operation up to timestamp 1731418619. Deleted 0 blocks up to #23773081. 
2025-11-12 14:37:13.4787|INFO|Merge.Plugin.Handlers.ForkchoiceUpdatedHandler|18|Received ForkChoice: 23783489 (0x92cc7f...701846), Safe: 23783453 (0x63bf8d...cc316c), Finalized: 23783421 (0xfde4ea...920e88) 
2025-11-12 14:37:13.4787|INFO|Merge.Plugin.Handlers.ForkchoiceUpdatedHandler|18|Synced Chain Head to 23783489 (0x92cc7f...701846) 
2025-11-12 14:37:24.8444|INFO|Merge.Plugin.Handlers.NewPayloadHandler|41|Received New Block:  23783490 (0x691f3e...69e455)      | limit    45,000,000    | Extra Data: BuilderNet (Nethermind) 
2025-11-12 14:37:25.6931|INFO|Consensus.Processing.ProcessingStats|90|Processed            23783490         |      812.9 ms  | slot         12,777 ms |⛽ Gas gwei: 0.12 .. 0.49 (0.83) .. 5.14 
2025-11-12 14:37:25.6931|INFO|Consensus.Processing.ProcessingStats|90| Block    0.0264 ETH    44.98 MGas    |      288   txs | calls      4,148 ( 75) | sload  12,488 | sstore  3,330 | create   1 
2025-11-12 14:37:25.6931|INFO|Consensus.Processing.ProcessingStats|90| Block throughput       55.33 MGas/s  |      354.3 tps | blobs   0 | exec code cache   8,381 | new     34 | ops   2,645,488 
2025-11-12 14:37:25.6951|ERROR|Consensus.Processing.BlockchainProcessor|41|BlockchainProcessor encountered an exception. System.InvalidOperationException: Unable to write to background task queue.
   at Nethermind.Consensus.Scheduler.BackgroundTaskScheduler.ScheduleTask[TReq](TReq request, Func`3 fulfillFunc, Nullable`1 timeout) in /nethermind/src/Nethermind/Nethermind.Consensus/Scheduler/BackgroundTaskScheduler.cs:line 196
   at Nethermind.History.HistoryPruner.SchedulePruneHistory(CancellationToken cancellationToken) in /nethermind/src/Nethermind/Nethermind.History/HistoryPruner.cs:line 242
   at Nethermind.Consensus.Processing.BlockchainProcessor.RunProcessingLoop() in /nethermind/src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 340
   at Nethermind.Consensus.Processing.BlockchainProcessor.RunProcessing() in /nethermind/src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 302
2025-11-12 14:37:26.4502|INFO|Merge.Plugin.Handlers.ForkchoiceUpdatedHandler|90|Received ForkChoice: 23783490 (0x691f3e...69e455), Safe: 23783453 (0x63bf8d...cc316c), Finalized: 23783421 (0xfde4ea...920e88) 
2025-11-12 14:37:26.4502|INFO|Merge.Plugin.Handlers.ForkchoiceUpdatedHandler|90|Synced Chain Head to 23783490 (0x691f3e...69e455) 
2025-11-12 14:37:36.6430|INFO|Merge.Plugin.Handlers.NewPayloadHandler|41|Received New Block:  23783491 (0xfdf73c...9fad31)      | limit    45,000,000    | Extra Data: BuilderNet (Beaver) 
2025-11-12 14:37:43.6480|INFO|Merge.Plugin.Handlers.NewPayloadHandler|86|Processing queue wasn't empty added to queue New Block:  23783491 (0xfdf73c...9fad31). 
2025-11-12 14:37:44.3286|INFO|Merge.Plugin.Handlers.ForkchoiceUpdatedHandler|86|Received ForkChoice: 23783491 (0xfdf73c...9fad31), Safe: 23783453 (0x63bf8d...cc316c), Finalized: 23783421 (0xfde4ea...920e88) 
2025-11-12 14:37:44.3286|INFO|Merge.Plugin.Handlers.ForkchoiceUpdatedHandler|86|Processing 1 blocks, Request: ForkChoice: 23783491 (0xfdf73c...9fad31), Safe: 23783453 (0x63bf8d...cc316c), Finalized: 23783421 (0xfde4ea...920e88) 
2025-11-12 14:37:50.0808|INFO|Merge.Plugin.Handlers.NewPayloadHandler|86|Received New Block:  23783492 (0x822902...a57c36)      | limit    45,000,000    | Extra Data: Titan (titanbuilder.xyz) 
2025-11-12 14:37:50.0808|INFO|lambda_method298|86|BeaconPivot was null. Setting beacon pivot to 23783492 (0x822902671d0030a681e9638d98c0ccf3f070173c8cfd9c97a9105b782ea57c36) 
2025-11-12 14:37:50.0808|INFO|lambda_method298|86|New beacon pivot: 23783492 (0x822902671d0030a681e9638d98c0ccf3f070173c8cfd9c97a9105b782ea57c36) 
2025-11-12 14:37:50.0864|INFO|Merge.Plugin.Handlers.NewPayloadHandler|86|Syncing... Inserting block 23783492 (0x822902...a57c36). 
2025-11-12 14:37:50.2409|INFO|Merge.Plugin.Handlers.ForkchoiceUpdatedHandler|90|Received ForkChoice: 23783492 (0x822902...a57c36), Safe: 23783453 (0x63bf8d...cc316c), Finalized: 23783421 (0xfde4ea...920e88) 
2025-11-12 14:37:50.2409|INFO|Merge.Plugin.Handlers.ForkchoiceUpdatedHandler|90|Processing 1 blocks, Request: ForkChoice: 23783492 (0x822902...a57c36), Safe: 23783453 (0x63bf8d...cc316c), Finalized: 23783421 (0xfde4ea...920e88) 
2025-11-12 14:37:52.6352|INFO|Synchronization.Reporting.SyncReport|107|Peers: 45 | node diversity :  Nethermind (51 %), Reth (27 %), Geth (18 %), Unknown (4 %)

### PR DESCRIPTION
**Pull request by LukaszRozmej**
Resolves #9697

## Changes

- Rename `BackgroundTaskScheduler.ScheduleTask` -> `TryScheduleTask` and avoid exceptions
- In `HistoryPruner` add checks before going into lock and doing pruning.
- In `HistoryPruner` make pruning task exclusive - don't schedule another before previous isn't finished.
- Remove lock from `BackgroundTaskScheduler`
- Move `CancelledToken` out of generic type
- Specify channel options explicitly

#### What types of changes does your code introduce?

- [x] Bugfix (a non-breaking change that fixes an issue)
- [x] Optimization
- [x] Refactoring

#### Requires testing

- [x] Yes

#### If yes, did you write tests?

- [x] No

#### Notes on testing

- Test normal node operation (`BackgroundTaskScheduler` won't be throwing exceptions which can affect networking a bit?)
- Test History pruning

### CODE REVIEW

File: src/Nethermind/Nethermind.Consensus/Scheduler/BackgroundTaskScheduler.cs [hunk 1]
```diff
@@ -48,6 +45,15 @@ public class BackgroundTaskScheduler : IBackgroundTaskScheduler, IAsyncDisposabl
     private CancellationTokenSource _blockProcessorCancellationTokenSource;
     private bool _disposed = false;
 
+    private static CancellationToken CancelledToken { get; } = CreateCancelledToken();
```
Comment (benaadams) [inline src/Nethermind/Nethermind.Consensus/Scheduler/BackgroundTaskScheduler.cs]: I think we do this somewhere else; should centralize in .Core somewhere?

Comment (benaadams) [reply src/Nethermind/Nethermind.Consensus/Scheduler/BackgroundTaskScheduler.cs]: Though maybe it was this code

File: src/Nethermind/Nethermind.Consensus/Scheduler/BackgroundTaskScheduler.cs [hunk 2]
```diff
@@ -158,51 +170,37 @@ private async Task StartChannel()
...
-                if (success)
-                {
-                    Interlocked.Increment(ref _queueCount);
-                }
+                UpdateQueueCount();
+            }
+            else
+            {
+                Interlocked.Decrement(ref _queueCount);
+                request.TryDispose();
```
Comment (benaadams) [inline src/Nethermind/Nethermind.Consensus/Scheduler/BackgroundTaskScheduler.cs]: Add `_logger.Warn` that queue is full; maybe with timestamp check so min time between warns is 10sec rather than doing it every millisecond (as should never happen, so we really need to know if it is)

File: src/Nethermind/Nethermind.History/HistoryPruner.cs [hunk 3]
```diff
@@ -242,38 +245,69 @@ private void OnBlockProcessorQueueEmpty(object? sender, EventArgs e)
         => SchedulePruneHistory(_processExitSource.Token);
 
     private void SchedulePruneHistory(CancellationToken cancellationToken)
-        => _backgroundTaskScheduler.ScheduleTask(1,
-            (_, backgroundTaskToken) =>
+    {
+        Task.Run(() =>
+        {
+            if (Interlocked.CompareExchange(ref _currentlyPruning, 1, 0) == 1)
```
Comment (benaadams) [inline src/Nethermind/Nethermind.History/HistoryPruner.cs]: Outside `Task.Run`; so don't queue on threadpool if active

File: src/Nethermind/Nethermind.Consensus/Scheduler/BackgroundTaskScheduler.cs (hunk 1 above)
Comment (LukaszRozmej) [reply src/Nethermind/Nethermind.Consensus/Scheduler/BackgroundTaskScheduler.cs]: `CancellationTokenExtensions`

File: src/Nethermind/Nethermind.History/HistoryPruner.cs [hunk 4]
```diff
@@ -210,7 +211,7 @@ public BlockHeader? OldestBlockHeader
             if (!_hasLoadedDeletePointer)
             {
                 bool lockTaken = false;
-                // take lock before updating delete pointer
+                // take lock before updating delete the pointer
```
[the remark this answers is not in the document]
Comment (Marchhill) [reply src/Nethermind/Nethermind.History/HistoryPruner.cs]: remove change

File: src/Nethermind/Nethermind.History/HistoryPruner.cs [hunk 5]
```diff
@@ -242,38 +245,69 @@ private void OnBlockProcessorQueueEmpty(object? sender, EventArgs e)
...
+                            finally
+                            {
+                                Interlocked.Exchange(ref _currentlyPruning, 0);
+                            }
 
-    internal Task TryPruneHistory(CancellationToken cancellationToken)
+                            return Task.CompletedTask;
+                        }))
+                {
+                    Interlocked.Exchange(ref _currentlyPruning, 0);
```
Comment (Marchhill) [inline src/Nethermind/Nethermind.History/HistoryPruner.cs]: If we failed to schedule pruning because there is a running task, then we shouldn't set `currentlyPruning` to 0?

File: src/Nethermind/Nethermind.History/HistoryPruner.cs (hunk 3 above)
Comment (LukaszRozmej) [reply src/Nethermind/Nethermind.History/HistoryPruner.cs]: Decided on Violitile.Read
I want actual field manipulation to be local to same method to handle failures.

Comment (Marchhill) [reply src/Nethermind/Nethermind.History/HistoryPruner.cs]: Agreed, also shouldn't this be `== 0`? The original value of `_currentlyPruning` is returned so we should only schedule if it wasn't running. Also nitpick: would be good to wrap these interlocked statements in small functions like `CheckIsPruning` or something for clarity

File: src/Nethermind/Nethermind.History/HistoryPruner.cs [hunk 6]
```diff
@@ -242,38 +245,81 @@ private void OnBlockProcessorQueueEmpty(object? sender, EventArgs e)
...
+            !ShouldPruneHistory(out ulong? cutoffTimestamp))
+        {
+            SkipLocalPruning();
+            return;
+        }
+
         bool lockTaken = false;
+        Monitor.TryEnter(_pruneLock, LockWaitTimeoutMs, ref lockTaken);
         try
         {
```
Comment (Marchhill) [inline src/Nethermind/Nethermind.History/HistoryPruner.cs:307]: was written in this way to avoid calling the `CutoffBlockNumber` getter twice

File: src/Nethermind/Nethermind.History/HistoryPruner.cs [hunk 7]
```diff
@@ -242,38 +245,81 @@ private void OnBlockProcessorQueueEmpty(object? sender, EventArgs e)
...
-        => _backgroundTaskScheduler.ScheduleTask(1,
-            (_, backgroundTaskToken) =>
+    {
+        if (Volatile.Read(ref _currentlyPruning) == 0)
+        {
+            Task.Run(() =>
             {
-                var cts = CancellationTokenSource.CreateLinkedTokenSource(backgroundTaskToken, cancellationToken);
-                return TryPruneHistory(cts.Token);
+                if (Interlocked.CompareExchange(ref _currentlyPruning, 1, 0) == 0)
```
[the remark this answers is not in the document]
Comment (LukaszRozmej) [reply src/Nethermind/Nethermind.History/HistoryPruner.cs:258]: @copilot but this is an optimization, I would like to not schedule a Task when I'm sure it won't proceed. I'm fine for multiple threads to schedule it and only one of them winning.

File: src/Nethermind/Nethermind.History/HistoryPruner.cs (hunk 3 above)
Comment (LukaszRozmej) [reply src/Nethermind/Nethermind.History/HistoryPruner.cs]: yep already fixed

File: src/Nethermind/Nethermind.History/HistoryPruner.cs (hunk 7 above)
[the remark this answers is not in the document]
Comment (Marchhill) [reply src/Nethermind/Nethermind.History/HistoryPruner.cs:258]: nice chat between two AI ;)

File: src/Nethermind/Nethermind.History/HistoryPruner.cs (hunk 5 above)
Comment (LukaszRozmej) [reply src/Nethermind/Nethermind.History/HistoryPruner.cs]: we failed here because the queue is full, we need to release the lock

File: src/Nethermind/Nethermind.History/HistoryPruner.cs (hunk 6 above)
Comment (LukaszRozmej) [reply src/Nethermind/Nethermind.History/HistoryPruner.cs:307]: changed, but `CutoffBlockNumber` is called:
- in `PruneBlocksAndReceipts` in the loop(!)
- `BodiesSyncFeed`
- `ReceiptsSyncFeed`

It looks very complicated and is locking (maybe a deadlock?)

Can you review it, maybe we can make it simpler.

File: src/Nethermind/Nethermind.History/HistoryPruner.cs [hunk 8]
```diff
@@ -242,38 +250,82 @@ private void OnBlockProcessorQueueEmpty(object? sender, EventArgs e)
         => SchedulePruneHistory(_processExitSource.Token);
 
     private void SchedulePruneHistory(CancellationToken cancellationToken)
-        => _backgroundTaskScheduler.ScheduleTask(1,
-            (_, backgroundTaskToken) =>
+    {
+        if (Volatile.Read(ref _currentlyPruning) == 0)
```
Comment (Marchhill) [inline src/Nethermind/Nethermind.History/HistoryPruner.cs:254]: why check twice and not move compareexchange here?

**Review by Marchhill — APPROVED** [review]

File: src/Nethermind/Nethermind.History/HistoryPruner.cs (hunk 8 above)
Comment (LukaszRozmej) [reply src/Nethermind/Nethermind.History/HistoryPruner.cs:254]: https://github.com/NethermindEth/nethermind/pull/9677#discussion_r2509997260

Violitile.Read should cover ~100% of practical use cases here. And it is easier to make consistent use on single-method level here for failures.

**Review by benaadams — APPROVED** [review]
