### PR TITLE
Fix tx index was removed during reorg

### LINKED ISSUE #6182: erroneous null JSON-RPC result for eth_getTransactionReceipt for one particular transaction hash
**Description**
I am querying a specific transaction hash `0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc` for its receipt and the json-rpc is returning null instead of the receipt. I have tried this on two separate nethermind nodes, same result.

**Steps to Reproduce**
In order to replicate the behavior, please provide a detailed list of steps:
1. ```curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc"],"id":1} $SERVER```
2. view result

**Actual behavior**
Response: ```{"jsonrpc":"2.0","result":null,"id":1}```

**Expected behavior**
Response: 

```
{"jsonrpc":"2.0","id":1,"result":{"blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","blockNumber":"0x1caf8dc","contractAddress":null,"cumulativeGasUsed":"0x1820dc3","effectiveGasPrice":"0x3b9aca0d","from":"0xe1e7b60d27b1820733d94fa6a79dde1a6c82987b","gasUsed":"0xed54e7","logs":[{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e10645f","0x0000000000000000000000001188a3a54b143be2bc5ab5faecf9fde934b3720e"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000310000000000000000000000000000000000000000000000000000000000000032","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9d9","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e10645f","0x0000000000000000000000001188a3a54b143be2bc5ab5faecf9fde934b3721d"],"data":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000008e000000000000000000000000000000000000000000000000000000000000008f","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9da","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e10645f","0x0000000000000000000000001188a3a54b143be2bc5ab5faecf9fde934b37224"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000650000000000000000000000000000000000000000000000000000000000000066","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9db","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e10645f","0x0000000000000000000000001188a3a54b143be2bc5ab5faecf9fde934c749e9"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000a700000000000000000000000000000000000000000000000000000000000000a8","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9dc","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e10645f","0x0000000000000000000000001188a3a54b143be2bc5ab5faecf9fde934c749d0"],"data":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000002600000000000000000000000000000000000000000000000000000000000000280000000000000000000000000000000000000000000000000000000000000027","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9dd","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e10645f","0x0000000000000000000000001188a3a54b143be2bc5ab5faecf9fde934c749ed"],"data":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000006e000000000000000000000000000000000000000000000000000000000000006f","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9de","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e10645f","0x0000000000000000000000001188a3a54b143be2bc5ab5faecf9fde934b37214"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000150000000000000000000000000000000000000000000000000000000000000016","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9df","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e053","0x0000000000000000000000001188a3a54b143be2cc33e6401c41d73fd9cf75d6"],"data":"0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000069000000000000000000000000000000000000000000000000000000000000006a000000000000000000000000000000000000000000000000000000000000006b","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9e0","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e053","0x0000000000000000000000001188a3a54b143be2cc33e6401c41d73fd9cf75d0"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000150000000000000000000000000000000000000000000000000000000000000016","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9e1","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e053","0x0000000000000000000000001188a3a54b143be2cc33e6401c41d73fd9cf75d5"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000650000000000000000000000000000000000000000000000000000000000000066","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9e2","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e053","0x0000000000000000000000001188a3a54b143be2cc33e6401c41d73fd9d2a56a"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000a700000000000000000000000000000000000000000000000000000000000000a8","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9e3","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e053","0x0000000000000000000000001188a3a54b143be2cc33e6401c41d73fd9cf75c5"],"data":"0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000009000000000000000000000000000000000000000000000000000000000000000a","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9e4","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e053","0x0000000000000000000000001188a3a54b143be2cc33e6401c41d73fd9d2a556"],"data":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000002600000000000000000000000000000000000000000000000000000000000000280000000000000000000000000000000000000000000000000000000000000027","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9e5","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e053","0x0000000000000000000000001188a3a54b143be2cc33e6401c41d73fd9d2a567"],"data":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000006e000000000000000000000000000000000000000000000000000000000000006f","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9e6","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e053","0x0000000000000000000000001188a3a54b143be2cc33e6401c41d73fd9cf75c4"],"data":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000001d000000000000000000000000000000000000000000000000000000000000001f000000000000000000000000000000000000000000000000000000000000001e","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9e7","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e053","0x0000000000000000000000001188a3a54b143be2cc33e6401c41d73fd9cf75d4"],"data":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000006c000000000000000000000000000000000000000000000000000000000000006d","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9e8","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e053","0x0000000000000000000000001188a3a54b143be2cc33e6401c41d73fd9cf75bf"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000330000000000000000000000000000000000000000000000000000000000000034","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9e9","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e053","0x0000000000000000000000001188a3a54b143be2cc33e6401c41d73fd9d2a54a"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9ea","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e053","0x0000000000000000000000001188a3a54b143be2cc33e6401c41d73fd9d819f6"],"data":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004f0000000000000000000000000000000000000000000000000000000000000050","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9eb","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e053","0x0000000000000000000000001188a3a54b143be2cc33e6401c41d73fd9cf75c2"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000310000000000000000000000000000000000000000000000000000000000000032","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9ec","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e053","0x0000000000000000000000001188a3a54b143be2cc33e6401c41d73fd9cf75c0"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000170000000000000000000000000000000000000000000000000000000000000018","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9ed","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e053","0x0000000000000000000000001188a3a54b143be2cc33e6401c41d73fd9d819ff"],"data":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000005d000000000000000000000000000000000000000000000000000000000000005e","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9ee","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e053","0x0000000000000000000000001188a3a54b143be2cc33e6401c41d73fd9d819f9"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000550000000000000000000000000000000000000000000000000000000000000056","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9ef","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e053","0x0000000000000000000000001188a3a54b143be2cc33e6401c41d73fd9d819f8"],"data":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004d000000000000000000000000000000000000000000000000000000000000004e","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9f0","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e053","0x0000000000000000000000001188a3a54b143be2cc33e6401c41d73fd9cf75c3"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000350000000000000000000000000000000000000000000000000000000000000036","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9f1","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e053","0x0000000000000000000000001188a3a54b143be2cc33e6401c41d73fd9d81a00"],"data":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000005f0000000000000000000000000000000000000000000000000000000000000060","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9f2","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e053","0x0000000000000000000000001188a3a54b143be2cc33e6401c41d73fd9d819f7"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000530000000000000000000000000000000000000000000000000000000000000054","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9f3","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e053","0x0000000000000000000000001188a3a54b143be2cc33e6401c41d73fd9cf75d8"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000700000000000000000000000000000000000000000000000000000000000000071","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9f4","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e18e7c9","0x0000000000000000000000001188a3a54b143be2ce61ccb5f91da06dc34f8523"],"data":"0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000001ebb0000000000000000000000000000000000000000000000000000000000001ebc","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9f5","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e18e7c9","0x0000000000000000000000001188a3a54b143be2ce61ccb5f91da06dc34f8522"],"data":"0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000bab0000000000000000000000000000000000000000000000000000000000000bac","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9f6","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e18e7c9","0x0000000000000000000000001188a3a54b143be2ce61ccb5f91da06dc34f8524"],"data":"0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000001b770000000000000000000000000000000000000000000000000000000000001b78","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9f7","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e18e7ca","0x0000000000000000000000001188a3a54b143be2ce61ced412fe6a28758f8529"],"data":"0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000f2f0000000000000000000000000000000000000000000000000000000000000f30","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9f8","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e18e7ca","0x0000000000000000000000001188a3a54b143be2ce61ced412fe6a28758f852b"],"data":"0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000001b770000000000000000000000000000000000000000000000000000000000001b78","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9f9","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e18e7cd","0x0000000000000000000000001188a3a54b143be2ce61d52e60a0c7588c5789a9"],"data":"0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000001889000000000000000000000000000000000000000000000000000000000000188a","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9fa","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e18e7cd","0x0000000000000000000000001188a3a54b143be2ce61d52e60a0c7588c4f8531"],"data":"0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000001b770000000000000000000000000000000000000000000000000000000000001b78","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9fb","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e18e7cf","0x0000000000000000000000001188a3a54b143be2ce61d96a94625acdf0cf8534"],"data":"0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000c1f0000000000000000000000000000000000000000000000000000000000000c20","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9fc","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e18e7cf","0x0000000000000000000000001188a3a54b143be2ce61d96a94625acdf0cf8537"],"data":"0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000001b770000000000000000000000000000000000000000000000000000000000001b78","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9fd","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e18e7c8","0x0000000000000000000000001188a3a54b143be2ce61ca97df3cd6b3110f851e"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000013ed00000000000000000000000000000000000000000000000000000000000013ee","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9fe","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e18e7c8","0x0000000000000000000000001188a3a54b143be2ce61ca97df3cd6b3110f851c"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000013cb00000000000000000000000000000000000000000000000000000000000013cc","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0x9ff","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e18e7c8","0x0000000000000000000000001188a3a54b143be2ce61ca97df3cd6b3110f851f"],"data":"0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000001b770000000000000000000000000000000000000000000000000000000000001b78","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0xa00","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e18e7d0","0x0000000000000000000000001188a3a54b143be2ce61db88ae432488a30f853f"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000013850000000000000000000000000000000000000000000000000000000000001386","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0xa01","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e18e7d0","0x0000000000000000000000001188a3a54b143be2ce61db88ae432488a30f8540"],"data":"0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000001b770000000000000000000000000000000000000000000000000000000000001b78","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0xa02","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e18e7d0","0x0000000000000000000000001188a3a54b143be2ce61db88ae432488a30f853e"],"data":"0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000001a9a0000000000000000000000000000000000000000000000000000000000001a9b","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0xa03","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e12b","0x0000000000000000000000001188a3a54b143be2cc35afa5f1ec0cc63fd85600"],"data":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000005d000000000000000000000000000000000000000000000000000000000000005e","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0xa04","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e12b","0x0000000000000000000000001188a3a54b143be2cc35afa5f1ec0cc63fd855da"],"data":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004f0000000000000000000000000000000000000000000000000000000000000050","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0xa05","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e12b","0x0000000000000000000000001188a3a54b143be2cc35afa5f1ec0cc63fcafff9"],"data":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000001d000000000000000000000000000000000000000000000000000000000000001f000000000000000000000000000000000000000000000000000000000000001e","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0xa06","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e12b","0x0000000000000000000000001188a3a54b143be2cc35afa5f1ec0cc63fcafff3"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000330000000000000000000000000000000000000000000000000000000000000034","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0xa07","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e12b","0x0000000000000000000000001188a3a54b143be2cc35afa5f1ec0cc63fd855f8"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000550000000000000000000000000000000000000000000000000000000000000056","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0xa08","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e12b","0x0000000000000000000000001188a3a54b143be2cc35afa5f1ec0cc63fcaffea"],"data":"0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000069000000000000000000000000000000000000000000000000000000000000006a000000000000000000000000000000000000000000000000000000000000006b","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0xa09","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e12b","0x0000000000000000000000001188a3a54b143be2cc35afa5f1ec0cc63fd22652"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0xa0a","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e12b","0x0000000000000000000000001188a3a54b143be2cc35afa5f1ec0cc63fcaffe8"],"data":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000006c000000000000000000000000000000000000000000000000000000000000006d","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0xa0b","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e12b","0x0000000000000000000000001188a3a54b143be2cc35afa5f1ec0cc63fcafff7"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000350000000000000000000000000000000000000000000000000000000000000036","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0xa0c","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e12b","0x0000000000000000000000001188a3a54b143be2cc35afa5f1ec0cc63fcb0013"],"data":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000008e000000000000000000000000000000000000000000000000000000000000008f","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0xa0d","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e12b","0x0000000000000000000000001188a3a54b143be2cc35afa5f1ec0cc63fcafffb"],"data":"0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000009000000000000000000000000000000000000000000000000000000000000000a","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0xa0e","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e12b","0x0000000000000000000000001188a3a54b143be2cc35afa5f1ec0cc63fcafff4"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000170000000000000000000000000000000000000000000000000000000000000018","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0xa0f","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e12b","0x0000000000000000000000001188a3a54b143be2cc35afa5f1ec0cc63fcaffe9"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000650000000000000000000000000000000000000000000000000000000000000066","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0xa10","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e12b","0x0000000000000000000000001188a3a54b143be2cc35afa5f1ec0cc63fcb0011"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000150000000000000000000000000000000000000000000000000000000000000016","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0xa11","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e12b","0x0000000000000000000000001188a3a54b143be2cc35afa5f1ec0cc63fd855fa"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000530000000000000000000000000000000000000000000000000000000000000054","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0xa12","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e12b","0x0000000000000000000000001188a3a54b143be2cc35afa5f1ec0cc63fcaffec"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000700000000000000000000000000000000000000000000000000000000000000071","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0xa13","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e12b","0x0000000000000000000000001188a3a54b143be2cc35afa5f1ec0cc63fd22667"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000a700000000000000000000000000000000000000000000000000000000000000a8","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0xa14","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e12b","0x0000000000000000000000001188a3a54b143be2cc35afa5f1ec0cc63fd22666"],"data":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000006e000000000000000000000000000000000000000000000000000000000000006f","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0xa15","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e12b","0x0000000000000000000000001188a3a54b143be2cc35afa5f1ec0cc63fd22655"],"data":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000002600000000000000000000000000000000000000000000000000000000000000280000000000000000000000000000000000000000000000000000000000000027","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0xa16","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e12b","0x0000000000000000000000001188a3a54b143be2cc35afa5f1ec0cc63fcafff5"],"data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000310000000000000000000000000000000000000000000000000000000000000032","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0xa17","removed":false},{"address":"0x0eaa5283990af9ca915b1d82261663d25d039d03","topics":["0x68571684e9afd137b1b6fd4d5e89203bb30bface5328e595a045ca89bac1fb69","0x000000000000000000000000000000000000000000000000000000005e17e12b","0x0000000000000000000000001188a3a54b143be2cc35afa5f1ec0cc63fd855f5"],"data":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004d000000000000000000000000000000000000000000000000000000000000004e","blockNumber":"0x1caf8dc","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","blockHash":"0x3a933e814f04a3a09b91e2c4922e35cb4c1d1a9d41fb8dffac9b5f8116f25039","logIndex":"0xa18","removed":false}],"logsBloom":"0xa40a06020000000000800000208000014280800000460000001000102810480000100000010500010080001000020050100000900003000300000010004000080000800210104022030408002020000200000000004084650200008018c10008002700424012000200004002040004101000448080640431e0000201808080040000201010000c040084c06480001008724000810001000002008020000000860020126080800002a00010810080004100420010001880002102800a000000020000e00008084400000300000100001000894000004000000002032000200a0000001090405000000888005000000000006000400000120018a0100000006010","status":"0x1","to":"0x80882c8638234d97b6c27a11562dc68727438d20","transactionHash":"0x0b4c848489bbd6e14a2833ed992eb191b9853a8fc7a01e70f4ac0b2d798464cc","transactionIndex":"0x7","type":"0x2"}}
```
as acquired from a public Erigon node via:

```
curl -X POST --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":67}' https://rpc.gnosis.gateway.fm
{"jsonrpc":"2.0","id":67,"result":"erigon/2.48.1/linux-amd64/go1.20.6"}
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x0b4c848489bbd6e14a2833ed992eb191b9853ahttps://rpc.gnosis.gateway.fm"id":1}' https://rpc.gnosis.gateway.fm
```

**Desktop (please complete the following information):**
```
curl --version
curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.16
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```

**Additional context**
My node version is: 
```
curl -X POST --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":67}' $SERVER
{"jsonrpc":"2.0","result":"Nethermind/v1.21.0+bb9b72c0/linux-x64/dotnet7.0.11","id":67}
```

**Logs**
Please include any relevant logs that may help identify the issue.

### PR DESCRIPTION
**Pull request by asdacap**
Fix #6182 

- I made a mistake. Was under the impression that the tx was later re-added. It was not.

## Changes

- Fix tx index removed after reorg.

#### What types of changes does your code introduce?

- [X] Bugfix (a non-breaking change that fixes an issue)

#### Requires testing

- [X] Yes
- [ ] No

#### If yes, did you write tests?

- [X] Yes
- [ ] No

#### Notes on testing

- Added a log to confirm the ordering. It was inserted before the added to main event.

### CODE REVIEW

**Review by benaadams — APPROVED** [review]

File: src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs [hunk 1]
```diff
@@ -364,11 +364,20 @@ public void EnsureCanonical(Block block)
...
 
-        private void RemoveBlockTx(Block block)
+        private void RemoveBlockTx(Block block, Block? exceptBlock = null)
         {
+            HashSet<Keccak> newTxs = null;
+            if (exceptBlock is not null)
+            {
+                newTxs = new HashSet<Keccak>(exceptBlock.Transactions.Select((tx) => tx.Hash));
+            }
+
```
Comment (LukaszRozmej) [inline src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs:374]: Just wondering if building HashSet is optimal here

Comment (asdacap) [reply src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs:374]: What do you have in mind?

Comment (LukaszRozmej) [reply src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs:374]: can we avoid allocation, what would have best performance

Comment (asdacap) [reply src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs:374]: Hmm.... Usually exceptBlock would be null, so I think its probably fine.
