### PR TITLE
catch OperationCanceledException in some cases

### LINKED ISSUE #4989: [Graceful shutdown] When node stopped on OldBodies, exception occurs
**To Reproduce**
1. Start syncing Mainnet
2. When node reach OldBodies stage stop a node using CTRL+C

**Actual behavior**
Exception visible:
```
2022-12-08 15:18:36.1745|INFO|220|Peer Manager shutdown complete.. please wait for all components to close
2022-12-08 15:18:36.1745|INFO|220|Stopping synchronizer...
2022-12-08 15:18:36.1774|WARN|220|Failure when executing request System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Nethermind.Network.P2P.ProtocolHandlers.ZeroProtocolHandlerBase.HandleResponse[TRequest,TResponse](Request`2 request, TransferSpeedType speedType, Func`2 describeRequestFunc, CancellationToken token) in /root/src/nethermind/src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/ZeroProtocolHandlerBase.cs:line 82
   at Nethermind.Network.P2P.Subprotocols.Eth.V66.Eth66ProtocolHandler.SendRequestGenericEth66[T66,TRequest,TResponse](MessageDictionary`3 messageQueue, T66 message, TransferSpeedType speedType, Func`2 describeRequestFunc, CancellationToken token) in /root/src/nethermind/src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V66/Eth66ProtocolHandler.cs:line 288
   at Nethermind.Network.P2P.Subprotocols.Eth.V66.Eth66ProtocolHandler.SendRequest(GetBlockBodiesMessage message, CancellationToken token) in /root/src/nethermind/src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V66/Eth66ProtocolHandler.cs:line 238
   at Nethermind.Network.P2P.ProtocolHandlers.SyncPeerProtocolHandlerBase.Nethermind.Blockchain.Synchronization.ISyncPeer.GetBlockBodies(IReadOnlyList`1 blockHashes, CancellationToken token) in /root/src/nethermind/src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/SyncPeerProtocolHandlerBase.cs:line 84
   at Nethermind.Synchronization.FastBlocks.BodiesSyncDispatcher.Dispatch(PeerInfo peerInfo, BodiesSyncBatch batch, CancellationToken cancellationToken) in /root/src/nethermind/src/Nethermind/Nethermind.Synchronization/FastBlocks/BodiesSyncDispatcher.cs:line 54
   at Nethermind.Synchronization.ParallelSync.SyncDispatcher`1.DoDispatch(CancellationToken cancellationToken, PeerInfo allocatedPeer, T request, SyncPeerAllocation allocation) in /root/src/nethermind/src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncDispatcher.cs:line 159
2022-12-08 15:18:36.1774|WARN|220|Failure when executing request System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Nethermind.Network.P2P.ProtocolHandlers.ZeroProtocolHandlerBase.HandleResponse[TRequest,TResponse](Request`2 request, TransferSpeedType speedType, Func`2 describeRequestFunc, CancellationToken token) in /root/src/nethermind/src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/ZeroProtocolHandlerBase.cs:line 82
   at Nethermind.Network.P2P.Subprotocols.Eth.V66.Eth66ProtocolHandler.SendRequestGenericEth66[T66,TRequest,TResponse](MessageDictionary`3 messageQueue, T66 message, TransferSpeedType speedType, Func`2 describeRequestFunc, CancellationToken token) in /root/src/nethermind/src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V66/Eth66ProtocolHandler.cs:line 288
   at Nethermind.Network.P2P.Subprotocols.Eth.V66.Eth66ProtocolHandler.SendRequest(GetBlockBodiesMessage message, CancellationToken token) in /root/src/nethermind/src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V66/Eth66ProtocolHandler.cs:line 238
   at Nethermind.Network.P2P.ProtocolHandlers.SyncPeerProtocolHandlerBase.Nethermind.Blockchain.Synchronization.ISyncPeer.GetBlockBodies(IReadOnlyList`1 blockHashes, CancellationToken token) in
```

**Expected behavior**
Node should be stopped without any issue - to be investigated why is this happening on this stage

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: Nethermind master

### PR DESCRIPTION
**Pull request by smartprogrammer93**
Resolves #4989

## Changes

- handle some OperationCanceledException differently than general exceptions.

#### What types of changes does your code introduce?

- [x] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a fix or a feature that would cause existing functionality not to work as expected)
- [ ] Documentation update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional or API changes)
- [ ] Build-related changes
- [ ] Other: _description_ 

#### Requires testing

- [ ] Yes
- [x] No

#### If yes, did you write tests?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by LukaszRozmej** [comment]
Do you know example scenarios when they would be thrown?

File: src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncDispatcher.cs [hunk 1]
```diff
@@ -128,6 +128,10 @@ public async Task Start(CancellationToken cancellationToken)
             {
                 if (Logger.IsDebug) Logger.Debug($"{request} - concurrency limit reached. Peer: {allocatedPeer}");
             }
+            catch (OperationCanceledException)
+            {
```
Comment (rubo) [inline src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncDispatcher.cs:132]: Please change "cancelled" to "canceled".

File: src/Nethermind/Nethermind.Runner/Program.cs [hunk 2]
```diff
@@ -195,6 +195,10 @@ private static void Run(string[] args)
 
                     _ = await Task.WhenAny(_cancelKeySource.Task, _processExit.Task);
                 }
+                catch (OperationCanceledException)
+                {
+                    if (_logger.IsTrace) _logger.Trace("Runner operation was cancelled");
```
Comment (rubo) [inline src/Nethermind/Nethermind.Runner/Program.cs:200]: Please change "cancelled" to "canceled".

**Review by rubo — CHANGES_REQUESTED** [review]

**Review by rubo — APPROVED** [review]

**Review by LukaszRozmej — APPROVED** [review]
