### PR TITLE
Cancel sync properly on shutdown

### LINKED ISSUE #4049: Nethermind error when shutting down during snap sync
**Describe the bug**
I was testing snap sync on Mainnet and I had to shut it down mid sync. When I did Nethermind started to error for 20-30 seconds before it shut down.

**Config File**
I only changed the `Sync` Module
```
 "Sync": {
    "FastSync": true,
    "PivotNumber": 14800170,
    "PivotHash": "0x8da85317042d1647190e1fa2fab9dc2d53348eadf6864c97ec96f1b90043dd1c",
    "PivotTotalDifficulty": "49324253533971943518782",
    "FastBlocks": true,
    "AncientBodiesBarrier": 11052984,
    "AncientReceiptsBarrier": 11052984,
    "WitnessProtocolEnabled": true,
    "SnapSync": true
  },
```
**Screen Shots**
image

**Desktop (please complete the following information):**
 - Winsows 11
 - Nethermind 1.13.0 Release 

**Additional context**
I have the full logs if needed

### PR DESCRIPTION
**Pull request by flcl42**
Fixes | Closes | Resolves #4049

Fast headers sync requires heavy database writes on request preparation which was not interruptible before this fix

## Changes:
- Interrupt fast headers sync properly

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [x] Yes
- [ ] No

**In case you checked yes, did you write tests??**

- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by LukaszRozmej** [comment]
Not sure about this, how much time docker gives the application to gracefully terminate before it terminates it hard?

**Comment by LukaszRozmej** [comment]
What happens if not all data is flushed? How much time is needed on average to flush data? Which feed is the most problematic?

**Comment by asdacap** [comment]
`BlockDownloader` and `MergeBlockDownloader` is long running, meaning it's dispatch have a long running loop, you may want to check them out, pass a cancellation token to the dispatch or something.

**Comment by asdacap** [comment]
Nevermind, seems to have already been accounted for.

File: src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs [hunk 1]
```diff
@@ -180,19 +181,20 @@ protected virtual void PostFinishCleanUp()
...
 
-        private void HandleDependentBatches()
+        private void HandleDependentBatches(CancellationToken cancellationToken)
         {
             long? lowest = LowestInsertedBlockHeader?.Number;
             while (lowest.HasValue && _dependencies.TryRemove(lowest.Value - 1, out HeadersSyncBatch? dependentBatch))
             {
                 InsertHeaders(dependentBatch!);
                 lowest = LowestInsertedBlockHeader?.Number;
+                cancellationToken.ThrowIfCancellationRequested();
```
Comment (LukaszRozmej) [inline src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs:191]: Do we really want to throw instead of just checking if cancellation was requested?

File: src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncDispatcher.cs [hunk 2]
```diff
@@ -82,12 +74,13 @@ public async Task Start(CancellationToken cancellationToken)
...
                         }
 
-                        await (dormantTaskLocal?.Task ?? Task.CompletedTask);
+                        await (dormantTaskLocal?.Task ?? Task.CompletedTask).WaitAsync(cancellationToken);
                         if (Logger.IsDebug) Logger.Debug($"{GetType().Name} got activated.");
                     }
                     else if (currentStateLocal == SyncFeedState.Active)
                     {
-                        T request = await (Feed.PrepareRequest() ?? Task.FromResult<T>(default!)); // just to avoid null refs
+                        cancellationToken.ThrowIfCancellationRequested();
```
Comment (LukaszRozmej) [inline src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncDispatcher.cs:82]: Same here

**Review by LukaszRozmej — APPROVED** [review]

File: src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs (hunk 1 above)
Comment (LukaszRozmej) [reply src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs:191]: Where is this exception caught?

Comment (flcl42) [reply src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs:191]: In SyncDispatcher, changes Feed to Finished state

File: src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncDispatcher.cs (hunk 2 above)
Comment (flcl42) [reply src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncDispatcher.cs:82]: Caught below, my intention was to make everything based on cancellation of the token, so the code may choose the proper moment of interruption

File: src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncDispatcher.cs [hunk 3]
```diff
@@ -113,6 +106,11 @@ public async Task Start(CancellationToken cancellationToken)
                                     if (Logger.IsWarn) Logger.Warn($"Failure when executing request {t.Exception}");
                                 }
 
+                                if (cancellationToken.IsCancellationRequested)
+                                {
+                                    if (Logger.IsInfo) Logger.Info("Ignoring sync response as shutdown is requested.");
```
Comment (LukaszRozmej) [inline src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncDispatcher.cs:111]: Maybe this should be Debug/Trace?

**Review by LukaszRozmej — APPROVED** [review]

File: src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncDispatcher.cs [hunk 4]
```diff
@@ -113,6 +106,12 @@ public async Task Start(CancellationToken cancellationToken)
                                     if (Logger.IsWarn) Logger.Warn($"Failure when executing request {t.Exception}");
                                 }
 
+                                if (cancellationToken.IsCancellationRequested)
+                                {
+                                    if (Logger.IsDebug) Logger.Debug("Ignoring sync response as shutdown is requested.");
+                                    return;
+                                }
```
Comment (LukaszRozmej) [inline src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncDispatcher.cs:113]: I would put this inside the below try to still have call to `Free(allocation)`. It probably won't matter for shutdown but potentially if we have other places where we would like to cancel the sync - yes.
