### PR TITLE
Reduce contention inside RocksDB during OldReceipts

### LINKED ISSUE #4642: Attestations are being more often missed during OldBodies/OldReceipts stage - optimization
**Describe the bug**
We are seeing a issue with starting a Validator with staking before Node is fully synced (after StateNodes but before OldBodies/OldReceipts). We need to think about optimalization in that area.

**Potential improvements:**
1. Config flag to move OldBodies/OldReceipts before state. Drawback - Following chain procedure will be way much longer
2. Prioritize New blocks rather than OldBodies/OldReceipts with some locks- hard to say if this is achievable in short-term but should seems to be a good starting point

### PR DESCRIPTION
**Pull request by benaadams**
Resolves #4642

## Changes

- Lock around `_blockStore.Get` in `BlockTree` to move the contention outside of the RocksDB allocator (which then heavily hits other RocksDB processing like block processing) and into the calling code (OldReceipts/OldBodies)
- A better soltion would be to change the allocator to tcmalloc or Jemalloc however that is much more complicated especially factoring cross platform (will need to be building RocksDB from source and compiling in the allocator) https://github.com/NethermindEth/nethermind/issues/6107

Before

image

After

image

#### What types of changes does your code introduce?

- [x] Optimization

#### Requires testing

- [x] No

#### Requires explanation in Release Notes

- [x] Yes

Significantly reduces block processing times

## Remarks

On Windows was seeing block processing times of up to 24seconds, this brings it down to mostly in range with the occasional spike to 2secs

### CODE REVIEW

**Review by LukaszRozmej — COMMENTED** [review]
As it is in block tree it may bottleneck other use cases like json rpc - I'm not fan of this workaround, can we try changing allocator?
If not should we make this lock in Receipts Sync only?
In the past we were building rocks db so bringing it back shouldn't be too complicated. @rubo and @matilote should have knowledge about it.

File: src/Nethermind/Nethermind.Blockchain/BlockTree.cs [hunk 1]
```diff
@@ -1303,6 +1306,12 @@ private bool ShouldCache(long number)
             blockNumber ??= _headerStore.GetBlockNumber(blockHash);
             if (blockNumber is not null)
             {
+                // Although thread-safe, because the blocks are so large it causes a lot of contention
+                // on the allocator inside RocksDb; which then impacts block processing heavily, especially on Windows.
+                // We take the lock here instead to reduce contention on the allocator in the db.
+                // A better solution would be to change the allocator https://github.com/NethermindEth/nethermind/issues/6107
+                using var handle = _allocatorLock.Acquire();
+
                 block = _blockStore.Get(
```
Comment (asdacap) [inline src/Nethermind/Nethermind.Blockchain/BlockTree.cs:1315]: Probably should be in BlockStore. There is an extension method that also does the deserialization. Probably pass the lock into the method so that the deserialization is not locked.

**Comment by benaadams** [comment]
> Is this like a windows specific behaviour?

My traces are locks inside [RtlAllocateHeap](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-rtlallocateheap) which is Windows specific, so I assume the behaviour on Linux will be different.

image

File: src/Nethermind/Nethermind.Blockchain/BlockTree.cs (hunk 1 above)
Comment (benaadams) [reply src/Nethermind/Nethermind.Blockchain/BlockTree.cs:1315]: Will have allocated and deallocted returning the memory to the pool to be used for next block at this level? So also use less memory and not contend on free?

**Comment by asdacap** [comment]
Is this only during OldBodies/OldReceipts? What about after that?

**Comment by benaadams** [comment]
> Is this only during OldBodies/OldReceipts? What about after that?

Yes, is perfectly fine and back to normal after (with or without additional lock); is more in OldReceipts than OldBodies as OldBodies is just setting and not making large allocations; whereas OldReceipts is pulling all the Bodies out of the db so using the db allocator heavily

**Comment by benaadams** [comment]
> As it is in block tree it may bottleneck other use cases like json rpc

Which should prevent multiple concurrent json rpc requests for blocks bottlenecking block processing also?

**Comment by asdacap** [comment]
I assume oldreceipts slow down also?

**Comment by benaadams** [comment]
> I assume oldreceipts slow down also?

I think it was faster (on Windows); will try again.

However if the allocator is actually working better in parallel (e.g. tcmalloc or Jemalloc) then it would be slower since it makes it single thread at this point. Not sure how the default Linux allocator used by RocksDb performs.

**Comment by benaadams** [comment]
On Windows

Pre-change 9hrs 24mins for first 56% of blocks
```
2024-04-08 02:03:11|Old Receipts         68 / 19,592,894 (  0.00 %) | queue     3,421 | current            0 Blk/s | total           14 Blk/s 
2024-04-08 11:27:06|Old Receipts 10,924,099 / 19,592,894 ( 55.76 %) | queue    36,316 | current          913 Blk/s | total          323 Blk/s 
```
Post-change 56 mins for remaining 42%
```
2024-04-08 11:31:08|Old Receipts 11,086,303 / 19,592,894 ( 56.58 %) | queue     1,676 | current          414 Blk/s | total          368 Blk/s 
2024-04-08 12:27:14|Old Receipts 19,364,833 / 19,592,894 ( 98.84 %) | queue   228,029 | current           13 Blk/s | total        2,400 Blk/s 
```

File: src/Nethermind/Nethermind.Blockchain/BlockTree.cs [hunk 2]
```diff
@@ -1303,11 +1306,31 @@ private bool ShouldCache(long number)
             blockNumber ??= _headerStore.GetBlockNumber(blockHash);
             if (blockNumber is not null)
             {
-                block = _blockStore.Get(
-                    blockNumber.Value,
-                    blockHash,
-                    (options & BlockTreeLookupOptions.ExcludeTxHashes) != 0 ? RlpBehaviors.ExcludeHashes : RlpBehaviors.None,
-                    shouldCache: false);
+                if (OperatingSystem.IsWindows())
```
Comment (LukaszRozmej) [inline src/Nethermind/Nethermind.Blockchain/BlockTree.cs:1309]: Should we cache it in some static variable? Or maybe some generic over struct way so it gets hard compiled?

**Review by LukaszRozmej — APPROVED** [review]

File: src/Nethermind/Nethermind.Blockchain/BlockTree.cs (hunk 2 above)
Comment (benaadams) [reply src/Nethermind/Nethermind.Blockchain/BlockTree.cs:1309]: Its returns [a true/false const from runtime](https://github.com/dotnet/runtime/blob/8e2655b932f5f5e184d289982bdc516576df0981/src/libraries/System.Private.CoreLib/src/System/OperatingSystem.cs#L313), so will already do that 
image

Comment (benaadams) [reply src/Nethermind/Nethermind.Blockchain/BlockTree.cs:1309]: `[NonVersionable]` attribute means it can be inlined across libaries so at the "ready to run" publish step if targeting a platform
